// src/routes/$.tsx
import { createFileRoute, redirect } from '@tanstack/react-router'

const redirects: Record<string, string> = {
  '/blogs': '/blog',
  '/blogs/': '/blog',
  '/blogs/page/2/': '/blog',
  '/blogs/page/2': '/blog',
  '/diy-vs-professional-help-understanding-balcony-deck-repair/':'/blogs/DIY-vs-Professional-Help-Understanding-Balcony-Deck-Repair',
  '/diy-vs-professional-help-understanding-balcony-deck-repair':'/blogs/DIY-vs-Professional-Help-Understanding-Balcony-Deck-Repair',
  '/enjoy-your-deck-rain-or-shine-waterproofing-tips-for-los-angeles-homeowners/':'/blogs/Enjoy-Your-Deck-Rain-or-Shine-Waterproofing-Tips-for-Los-Angeles-Homeowners',
  '/enjoy-your-deck-rain-or-shine-waterproofing-tips-for-los-angeles-homeowners':'/blogs/Enjoy-Your-Deck-Rain-or-Shine-Waterproofing-Tips-for-Los-Angeles-Homeowners',
  '/how-to-choose-the-best-deck-stain/':'/blogs/How-to-Choose-the-Best-Deck-Stain',
  '/how-to-choose-the-best-deck-stain':'/blogs/How-to-Choose-the-Best-Deck-Stain',
  '/how-to-fix-peeling-or-cracked-waterproof-deck-coatings-liquid-rubber-vs-polyurethane/':'/blogs/How-to-Fix-Peeling-or-Cracked-Waterproof-Deck-Coatings-Liquid-Rubber-vs-Polyurethane',
  '/how-to-fix-peeling-or-cracked-waterproof-deck-coatings-liquid-rubber-vs-polyurethane':'/blogs/How-to-Fix-Peeling-or-Cracked-Waterproof-Deck-Coatings-Liquid-Rubber-vs-Polyurethane',

  '/how-waterproofing-services-protect-your-home-from-long-term-damage/':'/blogs/How-Waterproofing-Services-Protect-Your-Home-from-Long-Term-Damage',
  '/how-waterproofing-services-protect-your-home-from-long-term-damage':'/blogs/How-Waterproofing-Services-Protect-Your-Home-from-Long-Term-Damage',
  '/preventing-water-intrusion-the-importance-of-balcony-leak-detection/':'/blogs/Preventing-Water-Intrusion-The-Importance-of-Balcony-Leak-Detection',
  '/preventing-water-intrusion-the-importance-of-balcony-leak-detection':'/blogs/Preventing-Water-Intrusion-The-Importance-of-Balcony-Leak-Detection',

  '/protecting-your-home-the-importance-of-balcony-leak-detection-and-repair/':'/blogs/Protecting-Your-Home-The-Importance-of-Balcony-Leak-Detection-and-Repair',
  '/protecting-your-home-the-importance-of-balcony-leak-detection-and-repair':'/blogs/Protecting-Your-Home-The-Importance-of-Balcony-Leak-Detection-and-Repair',

  '/safety-and-aesthetics-the-importance-of-timely-pool-decking-repair-in-santa-monica/':'/blogs/Safety-and-Aesthetics-The-Importance-of-Timely-Pool-Decking-Repair-in-Santa-Monica',
  '/safety-and-aesthetics-the-importance-of-timely-pool-decking-repair-in-santa-monica':'/blogs/Safety-and-Aesthetics-The-Importance-of-Timely-Pool-Decking-Repair-in-Santa-Monica',

  '/signs-of-balcony-deck-damage-when-to-consider-balcony-deck-repair/':'/blogs/Signs-of-Balcony-Deck-Damage-When-to-Consider-Balcony-Deck-Repair',
  '/signs-of-balcony-deck-damage-when-to-consider-balcony-deck-repair':'/blogs/Signs-of-Balcony-Deck-Damage-When-to-Consider-Balcony-Deck-Repair',

  '/the-benefits-of-professional-deck-sealant-for-long-term-deck-protection/':'/blogs/The-Benefits-of-Professional-Deck-Sealant-for-Long-Term-Deck-Protection',
  '/the-benefits-of-professional-deck-sealant-for-long-term-deck-protection':'/blogs/The-Benefits-of-Professional-Deck-Sealant-for-Long-Term-Deck-Protection',

  '/what-is-epoxy-flooring/':'/blogs/What-is-Epoxy-Flooring',
  '/what-is-epoxy-flooring':'/blogs/What-is-Epoxy-Flooring',

  '/what-is-pool-decking/':'/blogs/What-is-Pool-Decking',
  '/what-is-pool-decking':'/blogs/What-is-Pool-Decking',

  '/difference-between-interior-and-exterior-waterproofing-services/':'/blogs/What-Is-the-Difference-Between-Interior-and-Exterior-Waterproofing-Services',
  '/difference-between-interior-and-exterior-waterproofing-services':'/blogs/What-Is-the-Difference-Between-Interior-and-Exterior-Waterproofing-Services',

  '/what-is-waterproofing/':'/blogs/What-is-Waterproofing',
  '/what-is-waterproofing':'/blogs/What-is-Waterproofing',

  '/when-should-you-reapply-or-upgrade-waterproofing-solutions/':'/blogs/When-Should-You-Reapply-or-Upgrade-Waterproofing-Solutions',
  '/when-should-you-reapply-or-upgrade-waterproofing-solutions':'/blogs/When-Should-You-Reapply-or-Upgrade-Waterproofing-Solutions',

  '/which-waterproof-deck-coating-wins/':'/blogs/Which-Waterproofing-Deck-Coating-Wins',
  '/which-waterproof-deck-coating-wins':'/blogs/Which-Waterproofing-Deck-Coating-Wins',

  '/why-commercial-buildings-need-waterproofing-services/':'/blogs/Why-Commercial-Buildings-Need-Waterproofing-Services',
  '/why-commercial-buildings-need-waterproofing-services':'/blogs/Why-Commercial-Buildings-Need-Waterproofing-Services',

  '/why-summer-is-the-best-time-to-waterproof-your-property/':'/blogs/Why-Summer-Is-the-Best-Time-to-Waterproof-Your-Property',
  '/why-summer-is-the-best-time-to-waterproof-your-property':'/blogs/Why-Summer-Is-the-Best-Time-to-Waterproof-Your-Property',

  '/why-waterproof-deck-coatings-are-essential-for-outdoor-living/':'/blogs/Why-Waterproof-Deck-Coatings-Are-Essential-for-Outdoor-Living',
  '/why-waterproof-deck-coatings-are-essential-for-outdoor-living':'/blogs/Why-Waterproof-Deck-Coatings-Are-Essential-for-Outdoor-Living',

  '/why-waterproofing-balcony-decks-saves-you-big-repairs/':'/blogs/Why-Waterproofing-Balcony-Decks-Saves-You-Big-Repairs',
  '/why-waterproofing-balcony-decks-saves-you-big-repairs':'/blogs/Why-Waterproofing-Balcony-Decks-Saves-You-Big-Repairs',

  '/contact-us/':'/contact',
  '/contact-us':'/contact',

  '/balcony-waterproofing-repair-in-los-angeles/':'/los-angeles-deck-waterproofing-contractor',
  '/balcony-waterproofing-repair-in-los-angeles':'/los-angeles-deck-waterproofing-contractor',
  '/deck-leak-repair-services-in-los-angeles/':'/los-angeles-deck-waterproofing-contractor',
  '/deck-leak-repair-services-in-los-angeles':'/los-angeles-deck-waterproofing-contractor',
  '/deck-waterproofing-in-los-angeles/':'/los-angeles-deck-waterproofing-contractor',
  '/deck-waterproofing-in-los-angeles':'/los-angeles-deck-waterproofing-contractor',
  '/pool-decking-repair-in-los-angeles/':'/los-angeles-deck-waterproofing-contractor',
  '/pool-decking-repair-in-los-angeles':'/los-angeles-deck-waterproofing-contractor',
  '/water-leak-detection-in-los-angeles/':'/los-angeles-deck-waterproofing-contractor',
  '/water-leak-detection-in-los-angeles':'/los-angeles-deck-waterproofing-contractor',
  '/waterproofing-services-in-los-angeles-ca/':'/los-angeles-deck-waterproofing-contractor',
  '/waterproofing-services-in-los-angeles-ca':'/los-angeles-deck-waterproofing-contractor',
  '/waterproofing-services-in-west-los-angeles-ca/':'/los-angeles-deck-waterproofing-contractor',
  '/waterproofing-services-in-west-los-angeles-ca':'/los-angeles-deck-waterproofing-contractor',

  '/waterproofing-services-in-pasadena-ca/':'/Pasadena-deck-waterproofing-contractor',
  '/waterproofing-services-in-pasadena-ca':'/Pasadena-deck-waterproofing-contractor',

  '/below-grade-waterproofing/':'/service',
  '/below-grade-waterproofing':'/service',
  '/between-slab-waterproofing/':'/service',
  '/between-slab-waterproofing':'/service',
  '/concrete-floor-leveling-santa-monica/':'/service',
  '/concrete-floor-leveling-santa-monica':'/service',
  '/decorative-coatings/':'/service',
  '/decorative-coatings':'/service',
  '/epoxy-coating/':'/service',
  '/epoxy-coating':'/service',
  '/services/':'/service',
  '/services':'/service',
  '/waterproofing-services-in-acton-ca/':'/service',
  '/waterproofing-services-in-acton-ca':'/service',
  '/stucco-repair-waterproofing/':'/service',
  '/stucco-repair-waterproofing':'/service',
  '/water-leak-detection-in-san-fernando-valley/':'/service',
  '/water-leak-detection-in-san-fernando-valley':'/service',
  '/water-leak-detection-in-santa-clarita-valley/':'/service',
  '/water-leak-detection-in-santa-clarita-valley':'/service',
  '/water-leak-detection-in-venice-ca/':'/service',
  '/water-leak-detection-in-venice-ca':'/service',
  '/water-leak-detection-santa-monica/':'/service',
  '/water-leak-detection-santa-monica':'/service',
  '/waterproofing-services-in-altadena-ca/':'/service',
  '/waterproofing-services-in-altadena-ca':'/service',
  '/waterproofing-services-in-beverly-hills-ca/':'/service',
  '/waterproofing-services-in-beverly-hills-ca':'/service',
  '/waterproofing-services-in-brentwood-ca/':'/service',
  '/waterproofing-services-in-brentwood-ca':'/service',
  '/waterproofing-services-in-eagle-rock-ca/':'/service',
  '/waterproofing-services-in-eagle-rock-ca':'/service',
  '/waterproofing-services-in-echo-park-ca/':'/service',
  '/waterproofing-services-in-echo-park-ca':'/service',
  '/waterproofing-services-in-encino-ca/':'/service',
  '/waterproofing-services-in-encino-ca':'/service',
  '/waterproofing-services-in-hollywood-ca/':'/service',
  '/waterproofing-services-in-hollywood-ca':'/service',
  '/waterproofing-services-in-malibu-ca/':'/service',
  '/waterproofing-services-in-malibu-ca':'/service',
  '/waterproofing-services-in-manhattan-beach-ca/':'/service',
  '/waterproofing-services-in-manhattan-beach-ca':'/service',
  '/waterproofing-services-in-marina-del-rey-ca/':'/service',
  '/waterproofing-services-in-marina-del-rey-ca':'/service',
  '/waterproofing-services-in-mar-vista-ca/':'/service',
  '/waterproofing-services-in-mar-vista-ca':'/service',
  '/waterproofing-services-in-pacific-palisades-ca/':'/service',
  '/waterproofing-services-in-pacific-palisades-ca':'/service',
  '/waterproofing-services-in-santa-clarita-ca/':'/service',
  '/waterproofing-services-in-santa-clarita-ca':'/service',
  '/waterproofing-services-in-santa-monica-ca/':'/service',
  '/waterproofing-services-in-santa-monica-ca':'/service',
  '/waterproofing-services-in-sherman-oaks-ca/':'/service',
  '/waterproofing-services-in-sherman-oaks-ca':'/service',
  '/waterproofing-services-in-topanga-canyon-ca/':'/service',
  '/waterproofing-services-in-topanga-canyon-ca':'/service',
  '/waterproofing-services-in-west-hollywood-ca/':'/service',
  '/waterproofing-services-in-west-hollywood-ca':'/service',
  '/waterproofing-services-in-westwood-ca/':'/service',
  '/waterproofing-services-in-westwood-ca':'/service',

  '/balcony-deck-repairing-service-in-venice-ca/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repairing-service-in-venice-ca':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-service-in-san-fernando-valley/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-service-in-san-fernando-valley':'/services/balcony-waterproofing-coating-repair',
  '/balcony-leak-detection-service-in-san-fernando-valley/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-leak-detection-service-in-san-fernando-valley':'/services/balcony-waterproofing-coating-repair',
  '/balcony-leak-detection-service-in-santa-clarita-valley/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-leak-detection-service-in-santa-clarita-valley':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-in-santa-clarita-valley/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-in-santa-clarita-valley':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-in-santa-monica/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-in-santa-monica':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-leak-detection/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-deck-repair-leak-detection':'/services/balcony-waterproofing-coating-repair',
  '/balcony-leak-repair-service-in-san-fernando-valley/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-leak-repair-service-in-san-fernando-valley':'/services/balcony-waterproofing-coating-repair',
  '/balcony-waterproofing-service-in-san-fernando-valley/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-waterproofing-service-in-san-fernando-valley':'/services/balcony-waterproofing-coating-repair',
  '/balcony-waterproofing-service-in-santa-clarita-valley/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-waterproofing-service-in-santa-clarita-valley':'/services/balcony-waterproofing-coating-repair',
  '/balcony-waterproofing-repair-in-santa-monica/':'/services/balcony-waterproofing-coating-repair',
  '/balcony-waterproofing-repair-in-santa-monica':'/services/balcony-waterproofing-coating-repair',

  '/deck-coating-in-santa-monica/':'/services/deck-waterproofing-coating-repair',
  '/deck-coating-in-santa-monica':'/services/deck-waterproofing-coating-repair',
  '/deck-coating-service-in-santa-clarita-valley/':'/services/deck-waterproofing-coating-repair',
  '/deck-coating-service-in-santa-clarita-valley':'/services/deck-waterproofing-coating-repair',
  '/deck-leakage-repair-service-in-san-fernando-valley/':'/services/deck-waterproofing-coating-repair',
  '/deck-leakage-repair-service-in-san-fernando-valley':'/services/deck-waterproofing-coating-repair',
  '/deck-leakage-repairs-in-santa-clarita-valley/':'/services/deck-waterproofing-coating-repair',
  '/deck-leakage-repairs-in-santa-clarita-valley':'/services/deck-waterproofing-coating-repair',
  '/deck-leak-repair-in-santa-monica/':'/services/deck-waterproofing-coating-repair',
  '/deck-leak-repair-in-santa-monica':'/services/deck-waterproofing-coating-repair',
  '/deck-waterproofing-in-san-fernando-valley/':'/services/deck-waterproofing-coating-repair',
  '/deck-waterproofing-in-san-fernando-valley':'/services/deck-waterproofing-coating-repair',
  '/deck-waterproofing-santa-monica/':'/services/deck-waterproofing-coating-repair',
  '/deck-waterproofing-santa-monica':'/services/deck-waterproofing-coating-repair',
  '/pool-deck-coatings/':'/services/deck-waterproofing-coating-repair',
  '/pool-deck-coatings':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repairing-service-in-san-fernando-valley/':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repairing-service-in-san-fernando-valley':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repairing-service-in-venice-ca/':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repairing-service-in-venice-ca':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repair-in-santa-monica/':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repair-in-santa-monica':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repair-service-in-santa-clarita-valley/':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-repair-service-in-santa-clarita-valley':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-service-in-san-fernando-valley-elevate-your-poolside-with-water-proofed/':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-service-in-san-fernando-valley-elevate-your-poolside-with-water-proofed':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-service-in-santa-clarita-valley/':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-service-in-santa-clarita-valley':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-service-in-venice-ca/':'/services/deck-waterproofing-coating-repair',
  '/pool-decking-service-in-venice-ca':'/services/deck-waterproofing-coating-repair',
  '/water-proof-deck-coating-in-san-fernando-valley/':'/services/deck-waterproofing-coating-repair',
  '/water-proof-deck-coating-in-san-fernando-valley':'/services/deck-waterproofing-coating-repair',
  '/waterproof-deck-coatings/':'/services/deck-waterproofing-coating-repair',
  '/waterproof-deck-coatings':'/services/deck-waterproofing-coating-repair',
  '/waterproofing-deck-in-santa-clarita-valley/':'/services/deck-waterproofing-coating-repair',
  '/waterproofing-deck-in-santa-clarita-valley':'/services/deck-waterproofing-coating-repair',

  '/planter-waterproofing/':'/services/planter-waterproofing-coating-repair',
  '/planter-waterproofing':'/services/planter-waterproofing-coating-repair',
  '/waterproofing-services-in-playa-del-rey-ca/':'/services/planter-waterproofing-coating-repair',
  '/waterproofing-services-in-playa-del-rey-ca':'/services/planter-waterproofing-coating-repair',

  '/customer-testimonials/':'/testimonials',
  '/customer-testimonials':'/testimonials'



}

export const Route = createFileRoute('/$')({
  loader: ({ location }) => {
    const target = redirects[location.pathname]
    if (target) {
      throw redirect({ to: target, statusCode: 301 })
    }
  },
  component: () => null,
})
