/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPlanterWaterproofingCoatingRepairRouteImport } from './routes/services/planter-waterproofing-coating-repair'
import { Route as ServicesDeckWaterproofingCoatingRepairRouteImport } from './routes/services/deck-waterproofing-coating-repair'
import { Route as ServicesBalconyWaterproofingCoatingRepairRouteImport } from './routes/services/balcony-waterproofing-coating-repair'
import { Route as blogBlog9RouteImport } from './routes/(blog)/blog-9'
import { Route as blogBlog8RouteImport } from './routes/(blog)/blog-8'
import { Route as blogBlog7RouteImport } from './routes/(blog)/blog-7'
import { Route as blogBlog6RouteImport } from './routes/(blog)/blog-6'
import { Route as blogBlog5RouteImport } from './routes/(blog)/blog-5'
import { Route as blogBlog4RouteImport } from './routes/(blog)/blog-4'
import { Route as blogBlog3RouteImport } from './routes/(blog)/blog-3'
import { Route as blogBlog20RouteImport } from './routes/(blog)/blog-20'
import { Route as blogBlog2RouteImport } from './routes/(blog)/blog-2'
import { Route as blogBlog19RouteImport } from './routes/(blog)/blog-19'
import { Route as blogBlog18RouteImport } from './routes/(blog)/blog-18'
import { Route as blogBlog17RouteImport } from './routes/(blog)/blog-17'
import { Route as blogBlog16RouteImport } from './routes/(blog)/blog-16'
import { Route as blogBlog15RouteImport } from './routes/(blog)/blog-15'
import { Route as blogBlog14RouteImport } from './routes/(blog)/blog-14'
import { Route as blogBlog13RouteImport } from './routes/(blog)/blog-13'
import { Route as blogBlog12RouteImport } from './routes/(blog)/blog-12'
import { Route as blogBlog11RouteImport } from './routes/(blog)/blog-11'
import { Route as blogBlog10RouteImport } from './routes/(blog)/blog-10'
import { Route as blogBlog1RouteImport } from './routes/(blog)/blog-1'

const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPlanterWaterproofingCoatingRepairRoute =
  ServicesPlanterWaterproofingCoatingRepairRouteImport.update({
    id: '/services/planter-waterproofing-coating-repair',
    path: '/services/planter-waterproofing-coating-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDeckWaterproofingCoatingRepairRoute =
  ServicesDeckWaterproofingCoatingRepairRouteImport.update({
    id: '/services/deck-waterproofing-coating-repair',
    path: '/services/deck-waterproofing-coating-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBalconyWaterproofingCoatingRepairRoute =
  ServicesBalconyWaterproofingCoatingRepairRouteImport.update({
    id: '/services/balcony-waterproofing-coating-repair',
    path: '/services/balcony-waterproofing-coating-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const blogBlog9Route = blogBlog9RouteImport.update({
  id: '/(blog)/blog-9',
  path: '/blog-9',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog8Route = blogBlog8RouteImport.update({
  id: '/(blog)/blog-8',
  path: '/blog-8',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog7Route = blogBlog7RouteImport.update({
  id: '/(blog)/blog-7',
  path: '/blog-7',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog6Route = blogBlog6RouteImport.update({
  id: '/(blog)/blog-6',
  path: '/blog-6',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog5Route = blogBlog5RouteImport.update({
  id: '/(blog)/blog-5',
  path: '/blog-5',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog4Route = blogBlog4RouteImport.update({
  id: '/(blog)/blog-4',
  path: '/blog-4',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog3Route = blogBlog3RouteImport.update({
  id: '/(blog)/blog-3',
  path: '/blog-3',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog20Route = blogBlog20RouteImport.update({
  id: '/(blog)/blog-20',
  path: '/blog-20',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog2Route = blogBlog2RouteImport.update({
  id: '/(blog)/blog-2',
  path: '/blog-2',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog19Route = blogBlog19RouteImport.update({
  id: '/(blog)/blog-19',
  path: '/blog-19',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog18Route = blogBlog18RouteImport.update({
  id: '/(blog)/blog-18',
  path: '/blog-18',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog17Route = blogBlog17RouteImport.update({
  id: '/(blog)/blog-17',
  path: '/blog-17',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog16Route = blogBlog16RouteImport.update({
  id: '/(blog)/blog-16',
  path: '/blog-16',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog15Route = blogBlog15RouteImport.update({
  id: '/(blog)/blog-15',
  path: '/blog-15',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog14Route = blogBlog14RouteImport.update({
  id: '/(blog)/blog-14',
  path: '/blog-14',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog13Route = blogBlog13RouteImport.update({
  id: '/(blog)/blog-13',
  path: '/blog-13',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog12Route = blogBlog12RouteImport.update({
  id: '/(blog)/blog-12',
  path: '/blog-12',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog11Route = blogBlog11RouteImport.update({
  id: '/(blog)/blog-11',
  path: '/blog-11',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog10Route = blogBlog10RouteImport.update({
  id: '/(blog)/blog-10',
  path: '/blog-10',
  getParentRoute: () => rootRouteImport,
} as any)
const blogBlog1Route = blogBlog1RouteImport.update({
  id: '/(blog)/blog-1',
  path: '/blog-1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/service': typeof ServiceRoute
  '/blog-1': typeof blogBlog1Route
  '/blog-10': typeof blogBlog10Route
  '/blog-11': typeof blogBlog11Route
  '/blog-12': typeof blogBlog12Route
  '/blog-13': typeof blogBlog13Route
  '/blog-14': typeof blogBlog14Route
  '/blog-15': typeof blogBlog15Route
  '/blog-16': typeof blogBlog16Route
  '/blog-17': typeof blogBlog17Route
  '/blog-18': typeof blogBlog18Route
  '/blog-19': typeof blogBlog19Route
  '/blog-2': typeof blogBlog2Route
  '/blog-20': typeof blogBlog20Route
  '/blog-3': typeof blogBlog3Route
  '/blog-4': typeof blogBlog4Route
  '/blog-5': typeof blogBlog5Route
  '/blog-6': typeof blogBlog6Route
  '/blog-7': typeof blogBlog7Route
  '/blog-8': typeof blogBlog8Route
  '/blog-9': typeof blogBlog9Route
  '/services/balcony-waterproofing-coating-repair': typeof ServicesBalconyWaterproofingCoatingRepairRoute
  '/services/deck-waterproofing-coating-repair': typeof ServicesDeckWaterproofingCoatingRepairRoute
  '/services/planter-waterproofing-coating-repair': typeof ServicesPlanterWaterproofingCoatingRepairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/service': typeof ServiceRoute
  '/blog-1': typeof blogBlog1Route
  '/blog-10': typeof blogBlog10Route
  '/blog-11': typeof blogBlog11Route
  '/blog-12': typeof blogBlog12Route
  '/blog-13': typeof blogBlog13Route
  '/blog-14': typeof blogBlog14Route
  '/blog-15': typeof blogBlog15Route
  '/blog-16': typeof blogBlog16Route
  '/blog-17': typeof blogBlog17Route
  '/blog-18': typeof blogBlog18Route
  '/blog-19': typeof blogBlog19Route
  '/blog-2': typeof blogBlog2Route
  '/blog-20': typeof blogBlog20Route
  '/blog-3': typeof blogBlog3Route
  '/blog-4': typeof blogBlog4Route
  '/blog-5': typeof blogBlog5Route
  '/blog-6': typeof blogBlog6Route
  '/blog-7': typeof blogBlog7Route
  '/blog-8': typeof blogBlog8Route
  '/blog-9': typeof blogBlog9Route
  '/services/balcony-waterproofing-coating-repair': typeof ServicesBalconyWaterproofingCoatingRepairRoute
  '/services/deck-waterproofing-coating-repair': typeof ServicesDeckWaterproofingCoatingRepairRoute
  '/services/planter-waterproofing-coating-repair': typeof ServicesPlanterWaterproofingCoatingRepairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/service': typeof ServiceRoute
  '/(blog)/blog-1': typeof blogBlog1Route
  '/(blog)/blog-10': typeof blogBlog10Route
  '/(blog)/blog-11': typeof blogBlog11Route
  '/(blog)/blog-12': typeof blogBlog12Route
  '/(blog)/blog-13': typeof blogBlog13Route
  '/(blog)/blog-14': typeof blogBlog14Route
  '/(blog)/blog-15': typeof blogBlog15Route
  '/(blog)/blog-16': typeof blogBlog16Route
  '/(blog)/blog-17': typeof blogBlog17Route
  '/(blog)/blog-18': typeof blogBlog18Route
  '/(blog)/blog-19': typeof blogBlog19Route
  '/(blog)/blog-2': typeof blogBlog2Route
  '/(blog)/blog-20': typeof blogBlog20Route
  '/(blog)/blog-3': typeof blogBlog3Route
  '/(blog)/blog-4': typeof blogBlog4Route
  '/(blog)/blog-5': typeof blogBlog5Route
  '/(blog)/blog-6': typeof blogBlog6Route
  '/(blog)/blog-7': typeof blogBlog7Route
  '/(blog)/blog-8': typeof blogBlog8Route
  '/(blog)/blog-9': typeof blogBlog9Route
  '/services/balcony-waterproofing-coating-repair': typeof ServicesBalconyWaterproofingCoatingRepairRoute
  '/services/deck-waterproofing-coating-repair': typeof ServicesDeckWaterproofingCoatingRepairRoute
  '/services/planter-waterproofing-coating-repair': typeof ServicesPlanterWaterproofingCoatingRepairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/service'
    | '/blog-1'
    | '/blog-10'
    | '/blog-11'
    | '/blog-12'
    | '/blog-13'
    | '/blog-14'
    | '/blog-15'
    | '/blog-16'
    | '/blog-17'
    | '/blog-18'
    | '/blog-19'
    | '/blog-2'
    | '/blog-20'
    | '/blog-3'
    | '/blog-4'
    | '/blog-5'
    | '/blog-6'
    | '/blog-7'
    | '/blog-8'
    | '/blog-9'
    | '/services/balcony-waterproofing-coating-repair'
    | '/services/deck-waterproofing-coating-repair'
    | '/services/planter-waterproofing-coating-repair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/service'
    | '/blog-1'
    | '/blog-10'
    | '/blog-11'
    | '/blog-12'
    | '/blog-13'
    | '/blog-14'
    | '/blog-15'
    | '/blog-16'
    | '/blog-17'
    | '/blog-18'
    | '/blog-19'
    | '/blog-2'
    | '/blog-20'
    | '/blog-3'
    | '/blog-4'
    | '/blog-5'
    | '/blog-6'
    | '/blog-7'
    | '/blog-8'
    | '/blog-9'
    | '/services/balcony-waterproofing-coating-repair'
    | '/services/deck-waterproofing-coating-repair'
    | '/services/planter-waterproofing-coating-repair'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/service'
    | '/(blog)/blog-1'
    | '/(blog)/blog-10'
    | '/(blog)/blog-11'
    | '/(blog)/blog-12'
    | '/(blog)/blog-13'
    | '/(blog)/blog-14'
    | '/(blog)/blog-15'
    | '/(blog)/blog-16'
    | '/(blog)/blog-17'
    | '/(blog)/blog-18'
    | '/(blog)/blog-19'
    | '/(blog)/blog-2'
    | '/(blog)/blog-20'
    | '/(blog)/blog-3'
    | '/(blog)/blog-4'
    | '/(blog)/blog-5'
    | '/(blog)/blog-6'
    | '/(blog)/blog-7'
    | '/(blog)/blog-8'
    | '/(blog)/blog-9'
    | '/services/balcony-waterproofing-coating-repair'
    | '/services/deck-waterproofing-coating-repair'
    | '/services/planter-waterproofing-coating-repair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ServiceRoute: typeof ServiceRoute
  blogBlog1Route: typeof blogBlog1Route
  blogBlog10Route: typeof blogBlog10Route
  blogBlog11Route: typeof blogBlog11Route
  blogBlog12Route: typeof blogBlog12Route
  blogBlog13Route: typeof blogBlog13Route
  blogBlog14Route: typeof blogBlog14Route
  blogBlog15Route: typeof blogBlog15Route
  blogBlog16Route: typeof blogBlog16Route
  blogBlog17Route: typeof blogBlog17Route
  blogBlog18Route: typeof blogBlog18Route
  blogBlog19Route: typeof blogBlog19Route
  blogBlog2Route: typeof blogBlog2Route
  blogBlog20Route: typeof blogBlog20Route
  blogBlog3Route: typeof blogBlog3Route
  blogBlog4Route: typeof blogBlog4Route
  blogBlog5Route: typeof blogBlog5Route
  blogBlog6Route: typeof blogBlog6Route
  blogBlog7Route: typeof blogBlog7Route
  blogBlog8Route: typeof blogBlog8Route
  blogBlog9Route: typeof blogBlog9Route
  ServicesBalconyWaterproofingCoatingRepairRoute: typeof ServicesBalconyWaterproofingCoatingRepairRoute
  ServicesDeckWaterproofingCoatingRepairRoute: typeof ServicesDeckWaterproofingCoatingRepairRoute
  ServicesPlanterWaterproofingCoatingRepairRoute: typeof ServicesPlanterWaterproofingCoatingRepairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/planter-waterproofing-coating-repair': {
      id: '/services/planter-waterproofing-coating-repair'
      path: '/services/planter-waterproofing-coating-repair'
      fullPath: '/services/planter-waterproofing-coating-repair'
      preLoaderRoute: typeof ServicesPlanterWaterproofingCoatingRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/deck-waterproofing-coating-repair': {
      id: '/services/deck-waterproofing-coating-repair'
      path: '/services/deck-waterproofing-coating-repair'
      fullPath: '/services/deck-waterproofing-coating-repair'
      preLoaderRoute: typeof ServicesDeckWaterproofingCoatingRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/balcony-waterproofing-coating-repair': {
      id: '/services/balcony-waterproofing-coating-repair'
      path: '/services/balcony-waterproofing-coating-repair'
      fullPath: '/services/balcony-waterproofing-coating-repair'
      preLoaderRoute: typeof ServicesBalconyWaterproofingCoatingRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-9': {
      id: '/(blog)/blog-9'
      path: '/blog-9'
      fullPath: '/blog-9'
      preLoaderRoute: typeof blogBlog9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-8': {
      id: '/(blog)/blog-8'
      path: '/blog-8'
      fullPath: '/blog-8'
      preLoaderRoute: typeof blogBlog8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-7': {
      id: '/(blog)/blog-7'
      path: '/blog-7'
      fullPath: '/blog-7'
      preLoaderRoute: typeof blogBlog7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-6': {
      id: '/(blog)/blog-6'
      path: '/blog-6'
      fullPath: '/blog-6'
      preLoaderRoute: typeof blogBlog6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-5': {
      id: '/(blog)/blog-5'
      path: '/blog-5'
      fullPath: '/blog-5'
      preLoaderRoute: typeof blogBlog5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-4': {
      id: '/(blog)/blog-4'
      path: '/blog-4'
      fullPath: '/blog-4'
      preLoaderRoute: typeof blogBlog4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-3': {
      id: '/(blog)/blog-3'
      path: '/blog-3'
      fullPath: '/blog-3'
      preLoaderRoute: typeof blogBlog3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-20': {
      id: '/(blog)/blog-20'
      path: '/blog-20'
      fullPath: '/blog-20'
      preLoaderRoute: typeof blogBlog20RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-2': {
      id: '/(blog)/blog-2'
      path: '/blog-2'
      fullPath: '/blog-2'
      preLoaderRoute: typeof blogBlog2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-19': {
      id: '/(blog)/blog-19'
      path: '/blog-19'
      fullPath: '/blog-19'
      preLoaderRoute: typeof blogBlog19RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-18': {
      id: '/(blog)/blog-18'
      path: '/blog-18'
      fullPath: '/blog-18'
      preLoaderRoute: typeof blogBlog18RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-17': {
      id: '/(blog)/blog-17'
      path: '/blog-17'
      fullPath: '/blog-17'
      preLoaderRoute: typeof blogBlog17RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-16': {
      id: '/(blog)/blog-16'
      path: '/blog-16'
      fullPath: '/blog-16'
      preLoaderRoute: typeof blogBlog16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-15': {
      id: '/(blog)/blog-15'
      path: '/blog-15'
      fullPath: '/blog-15'
      preLoaderRoute: typeof blogBlog15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-14': {
      id: '/(blog)/blog-14'
      path: '/blog-14'
      fullPath: '/blog-14'
      preLoaderRoute: typeof blogBlog14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-13': {
      id: '/(blog)/blog-13'
      path: '/blog-13'
      fullPath: '/blog-13'
      preLoaderRoute: typeof blogBlog13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-12': {
      id: '/(blog)/blog-12'
      path: '/blog-12'
      fullPath: '/blog-12'
      preLoaderRoute: typeof blogBlog12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-11': {
      id: '/(blog)/blog-11'
      path: '/blog-11'
      fullPath: '/blog-11'
      preLoaderRoute: typeof blogBlog11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-10': {
      id: '/(blog)/blog-10'
      path: '/blog-10'
      fullPath: '/blog-10'
      preLoaderRoute: typeof blogBlog10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(blog)/blog-1': {
      id: '/(blog)/blog-1'
      path: '/blog-1'
      fullPath: '/blog-1'
      preLoaderRoute: typeof blogBlog1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ServiceRoute: ServiceRoute,
  blogBlog1Route: blogBlog1Route,
  blogBlog10Route: blogBlog10Route,
  blogBlog11Route: blogBlog11Route,
  blogBlog12Route: blogBlog12Route,
  blogBlog13Route: blogBlog13Route,
  blogBlog14Route: blogBlog14Route,
  blogBlog15Route: blogBlog15Route,
  blogBlog16Route: blogBlog16Route,
  blogBlog17Route: blogBlog17Route,
  blogBlog18Route: blogBlog18Route,
  blogBlog19Route: blogBlog19Route,
  blogBlog2Route: blogBlog2Route,
  blogBlog20Route: blogBlog20Route,
  blogBlog3Route: blogBlog3Route,
  blogBlog4Route: blogBlog4Route,
  blogBlog5Route: blogBlog5Route,
  blogBlog6Route: blogBlog6Route,
  blogBlog7Route: blogBlog7Route,
  blogBlog8Route: blogBlog8Route,
  blogBlog9Route: blogBlog9Route,
  ServicesBalconyWaterproofingCoatingRepairRoute:
    ServicesBalconyWaterproofingCoatingRepairRoute,
  ServicesDeckWaterproofingCoatingRepairRoute:
    ServicesDeckWaterproofingCoatingRepairRoute,
  ServicesPlanterWaterproofingCoatingRepairRoute:
    ServicesPlanterWaterproofingCoatingRepairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
