/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPlanterWaterproofingCoatingRepairRouteImport } from './routes/services/planter-waterproofing-coating-repair'
import { Route as ServicesDeckWaterproofingCoatingRepairRouteImport } from './routes/services/deck-waterproofing-coating-repair'
import { Route as ServicesBalconyWaterproofingCoatingRepairRouteImport } from './routes/services/balcony-waterproofing-coating-repair'
import { Route as BlogsBlog9RouteImport } from './routes/blogs/blog-9'
import { Route as BlogsBlog8RouteImport } from './routes/blogs/blog-8'
import { Route as BlogsBlog7RouteImport } from './routes/blogs/blog-7'
import { Route as BlogsBlog6RouteImport } from './routes/blogs/blog-6'
import { Route as BlogsBlog5RouteImport } from './routes/blogs/blog-5'
import { Route as BlogsBlog4RouteImport } from './routes/blogs/blog-4'
import { Route as BlogsBlog3RouteImport } from './routes/blogs/blog-3'
import { Route as BlogsBlog20RouteImport } from './routes/blogs/blog-20'
import { Route as BlogsBlog2RouteImport } from './routes/blogs/blog-2'
import { Route as BlogsBlog19RouteImport } from './routes/blogs/blog-19'
import { Route as BlogsBlog18RouteImport } from './routes/blogs/blog-18'
import { Route as BlogsBlog17RouteImport } from './routes/blogs/blog-17'
import { Route as BlogsBlog16RouteImport } from './routes/blogs/blog-16'
import { Route as BlogsBlog15RouteImport } from './routes/blogs/blog-15'
import { Route as BlogsBlog14RouteImport } from './routes/blogs/blog-14'
import { Route as BlogsBlog13RouteImport } from './routes/blogs/blog-13'
import { Route as BlogsBlog12RouteImport } from './routes/blogs/blog-12'
import { Route as BlogsBlog11RouteImport } from './routes/blogs/blog-11'
import { Route as BlogsBlog10RouteImport } from './routes/blogs/blog-10'
import { Route as BlogsBlog1RouteImport } from './routes/blogs/blog-1'

const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPlanterWaterproofingCoatingRepairRoute =
  ServicesPlanterWaterproofingCoatingRepairRouteImport.update({
    id: '/services/planter-waterproofing-coating-repair',
    path: '/services/planter-waterproofing-coating-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDeckWaterproofingCoatingRepairRoute =
  ServicesDeckWaterproofingCoatingRepairRouteImport.update({
    id: '/services/deck-waterproofing-coating-repair',
    path: '/services/deck-waterproofing-coating-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBalconyWaterproofingCoatingRepairRoute =
  ServicesBalconyWaterproofingCoatingRepairRouteImport.update({
    id: '/services/balcony-waterproofing-coating-repair',
    path: '/services/balcony-waterproofing-coating-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsBlog9Route = BlogsBlog9RouteImport.update({
  id: '/blogs/blog-9',
  path: '/blogs/blog-9',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog8Route = BlogsBlog8RouteImport.update({
  id: '/blogs/blog-8',
  path: '/blogs/blog-8',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog7Route = BlogsBlog7RouteImport.update({
  id: '/blogs/blog-7',
  path: '/blogs/blog-7',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog6Route = BlogsBlog6RouteImport.update({
  id: '/blogs/blog-6',
  path: '/blogs/blog-6',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog5Route = BlogsBlog5RouteImport.update({
  id: '/blogs/blog-5',
  path: '/blogs/blog-5',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog4Route = BlogsBlog4RouteImport.update({
  id: '/blogs/blog-4',
  path: '/blogs/blog-4',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog3Route = BlogsBlog3RouteImport.update({
  id: '/blogs/blog-3',
  path: '/blogs/blog-3',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog20Route = BlogsBlog20RouteImport.update({
  id: '/blogs/blog-20',
  path: '/blogs/blog-20',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog2Route = BlogsBlog2RouteImport.update({
  id: '/blogs/blog-2',
  path: '/blogs/blog-2',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog19Route = BlogsBlog19RouteImport.update({
  id: '/blogs/blog-19',
  path: '/blogs/blog-19',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog18Route = BlogsBlog18RouteImport.update({
  id: '/blogs/blog-18',
  path: '/blogs/blog-18',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog17Route = BlogsBlog17RouteImport.update({
  id: '/blogs/blog-17',
  path: '/blogs/blog-17',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog16Route = BlogsBlog16RouteImport.update({
  id: '/blogs/blog-16',
  path: '/blogs/blog-16',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog15Route = BlogsBlog15RouteImport.update({
  id: '/blogs/blog-15',
  path: '/blogs/blog-15',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog14Route = BlogsBlog14RouteImport.update({
  id: '/blogs/blog-14',
  path: '/blogs/blog-14',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog13Route = BlogsBlog13RouteImport.update({
  id: '/blogs/blog-13',
  path: '/blogs/blog-13',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog12Route = BlogsBlog12RouteImport.update({
  id: '/blogs/blog-12',
  path: '/blogs/blog-12',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog11Route = BlogsBlog11RouteImport.update({
  id: '/blogs/blog-11',
  path: '/blogs/blog-11',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog10Route = BlogsBlog10RouteImport.update({
  id: '/blogs/blog-10',
  path: '/blogs/blog-10',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlog1Route = BlogsBlog1RouteImport.update({
  id: '/blogs/blog-1',
  path: '/blogs/blog-1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/service': typeof ServiceRoute
  '/blogs/blog-1': typeof BlogsBlog1Route
  '/blogs/blog-10': typeof BlogsBlog10Route
  '/blogs/blog-11': typeof BlogsBlog11Route
  '/blogs/blog-12': typeof BlogsBlog12Route
  '/blogs/blog-13': typeof BlogsBlog13Route
  '/blogs/blog-14': typeof BlogsBlog14Route
  '/blogs/blog-15': typeof BlogsBlog15Route
  '/blogs/blog-16': typeof BlogsBlog16Route
  '/blogs/blog-17': typeof BlogsBlog17Route
  '/blogs/blog-18': typeof BlogsBlog18Route
  '/blogs/blog-19': typeof BlogsBlog19Route
  '/blogs/blog-2': typeof BlogsBlog2Route
  '/blogs/blog-20': typeof BlogsBlog20Route
  '/blogs/blog-3': typeof BlogsBlog3Route
  '/blogs/blog-4': typeof BlogsBlog4Route
  '/blogs/blog-5': typeof BlogsBlog5Route
  '/blogs/blog-6': typeof BlogsBlog6Route
  '/blogs/blog-7': typeof BlogsBlog7Route
  '/blogs/blog-8': typeof BlogsBlog8Route
  '/blogs/blog-9': typeof BlogsBlog9Route
  '/services/balcony-waterproofing-coating-repair': typeof ServicesBalconyWaterproofingCoatingRepairRoute
  '/services/deck-waterproofing-coating-repair': typeof ServicesDeckWaterproofingCoatingRepairRoute
  '/services/planter-waterproofing-coating-repair': typeof ServicesPlanterWaterproofingCoatingRepairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/service': typeof ServiceRoute
  '/blogs/blog-1': typeof BlogsBlog1Route
  '/blogs/blog-10': typeof BlogsBlog10Route
  '/blogs/blog-11': typeof BlogsBlog11Route
  '/blogs/blog-12': typeof BlogsBlog12Route
  '/blogs/blog-13': typeof BlogsBlog13Route
  '/blogs/blog-14': typeof BlogsBlog14Route
  '/blogs/blog-15': typeof BlogsBlog15Route
  '/blogs/blog-16': typeof BlogsBlog16Route
  '/blogs/blog-17': typeof BlogsBlog17Route
  '/blogs/blog-18': typeof BlogsBlog18Route
  '/blogs/blog-19': typeof BlogsBlog19Route
  '/blogs/blog-2': typeof BlogsBlog2Route
  '/blogs/blog-20': typeof BlogsBlog20Route
  '/blogs/blog-3': typeof BlogsBlog3Route
  '/blogs/blog-4': typeof BlogsBlog4Route
  '/blogs/blog-5': typeof BlogsBlog5Route
  '/blogs/blog-6': typeof BlogsBlog6Route
  '/blogs/blog-7': typeof BlogsBlog7Route
  '/blogs/blog-8': typeof BlogsBlog8Route
  '/blogs/blog-9': typeof BlogsBlog9Route
  '/services/balcony-waterproofing-coating-repair': typeof ServicesBalconyWaterproofingCoatingRepairRoute
  '/services/deck-waterproofing-coating-repair': typeof ServicesDeckWaterproofingCoatingRepairRoute
  '/services/planter-waterproofing-coating-repair': typeof ServicesPlanterWaterproofingCoatingRepairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/service': typeof ServiceRoute
  '/blogs/blog-1': typeof BlogsBlog1Route
  '/blogs/blog-10': typeof BlogsBlog10Route
  '/blogs/blog-11': typeof BlogsBlog11Route
  '/blogs/blog-12': typeof BlogsBlog12Route
  '/blogs/blog-13': typeof BlogsBlog13Route
  '/blogs/blog-14': typeof BlogsBlog14Route
  '/blogs/blog-15': typeof BlogsBlog15Route
  '/blogs/blog-16': typeof BlogsBlog16Route
  '/blogs/blog-17': typeof BlogsBlog17Route
  '/blogs/blog-18': typeof BlogsBlog18Route
  '/blogs/blog-19': typeof BlogsBlog19Route
  '/blogs/blog-2': typeof BlogsBlog2Route
  '/blogs/blog-20': typeof BlogsBlog20Route
  '/blogs/blog-3': typeof BlogsBlog3Route
  '/blogs/blog-4': typeof BlogsBlog4Route
  '/blogs/blog-5': typeof BlogsBlog5Route
  '/blogs/blog-6': typeof BlogsBlog6Route
  '/blogs/blog-7': typeof BlogsBlog7Route
  '/blogs/blog-8': typeof BlogsBlog8Route
  '/blogs/blog-9': typeof BlogsBlog9Route
  '/services/balcony-waterproofing-coating-repair': typeof ServicesBalconyWaterproofingCoatingRepairRoute
  '/services/deck-waterproofing-coating-repair': typeof ServicesDeckWaterproofingCoatingRepairRoute
  '/services/planter-waterproofing-coating-repair': typeof ServicesPlanterWaterproofingCoatingRepairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/service'
    | '/blogs/blog-1'
    | '/blogs/blog-10'
    | '/blogs/blog-11'
    | '/blogs/blog-12'
    | '/blogs/blog-13'
    | '/blogs/blog-14'
    | '/blogs/blog-15'
    | '/blogs/blog-16'
    | '/blogs/blog-17'
    | '/blogs/blog-18'
    | '/blogs/blog-19'
    | '/blogs/blog-2'
    | '/blogs/blog-20'
    | '/blogs/blog-3'
    | '/blogs/blog-4'
    | '/blogs/blog-5'
    | '/blogs/blog-6'
    | '/blogs/blog-7'
    | '/blogs/blog-8'
    | '/blogs/blog-9'
    | '/services/balcony-waterproofing-coating-repair'
    | '/services/deck-waterproofing-coating-repair'
    | '/services/planter-waterproofing-coating-repair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/service'
    | '/blogs/blog-1'
    | '/blogs/blog-10'
    | '/blogs/blog-11'
    | '/blogs/blog-12'
    | '/blogs/blog-13'
    | '/blogs/blog-14'
    | '/blogs/blog-15'
    | '/blogs/blog-16'
    | '/blogs/blog-17'
    | '/blogs/blog-18'
    | '/blogs/blog-19'
    | '/blogs/blog-2'
    | '/blogs/blog-20'
    | '/blogs/blog-3'
    | '/blogs/blog-4'
    | '/blogs/blog-5'
    | '/blogs/blog-6'
    | '/blogs/blog-7'
    | '/blogs/blog-8'
    | '/blogs/blog-9'
    | '/services/balcony-waterproofing-coating-repair'
    | '/services/deck-waterproofing-coating-repair'
    | '/services/planter-waterproofing-coating-repair'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/service'
    | '/blogs/blog-1'
    | '/blogs/blog-10'
    | '/blogs/blog-11'
    | '/blogs/blog-12'
    | '/blogs/blog-13'
    | '/blogs/blog-14'
    | '/blogs/blog-15'
    | '/blogs/blog-16'
    | '/blogs/blog-17'
    | '/blogs/blog-18'
    | '/blogs/blog-19'
    | '/blogs/blog-2'
    | '/blogs/blog-20'
    | '/blogs/blog-3'
    | '/blogs/blog-4'
    | '/blogs/blog-5'
    | '/blogs/blog-6'
    | '/blogs/blog-7'
    | '/blogs/blog-8'
    | '/blogs/blog-9'
    | '/services/balcony-waterproofing-coating-repair'
    | '/services/deck-waterproofing-coating-repair'
    | '/services/planter-waterproofing-coating-repair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ServiceRoute: typeof ServiceRoute
  BlogsBlog1Route: typeof BlogsBlog1Route
  BlogsBlog10Route: typeof BlogsBlog10Route
  BlogsBlog11Route: typeof BlogsBlog11Route
  BlogsBlog12Route: typeof BlogsBlog12Route
  BlogsBlog13Route: typeof BlogsBlog13Route
  BlogsBlog14Route: typeof BlogsBlog14Route
  BlogsBlog15Route: typeof BlogsBlog15Route
  BlogsBlog16Route: typeof BlogsBlog16Route
  BlogsBlog17Route: typeof BlogsBlog17Route
  BlogsBlog18Route: typeof BlogsBlog18Route
  BlogsBlog19Route: typeof BlogsBlog19Route
  BlogsBlog2Route: typeof BlogsBlog2Route
  BlogsBlog20Route: typeof BlogsBlog20Route
  BlogsBlog3Route: typeof BlogsBlog3Route
  BlogsBlog4Route: typeof BlogsBlog4Route
  BlogsBlog5Route: typeof BlogsBlog5Route
  BlogsBlog6Route: typeof BlogsBlog6Route
  BlogsBlog7Route: typeof BlogsBlog7Route
  BlogsBlog8Route: typeof BlogsBlog8Route
  BlogsBlog9Route: typeof BlogsBlog9Route
  ServicesBalconyWaterproofingCoatingRepairRoute: typeof ServicesBalconyWaterproofingCoatingRepairRoute
  ServicesDeckWaterproofingCoatingRepairRoute: typeof ServicesDeckWaterproofingCoatingRepairRoute
  ServicesPlanterWaterproofingCoatingRepairRoute: typeof ServicesPlanterWaterproofingCoatingRepairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/planter-waterproofing-coating-repair': {
      id: '/services/planter-waterproofing-coating-repair'
      path: '/services/planter-waterproofing-coating-repair'
      fullPath: '/services/planter-waterproofing-coating-repair'
      preLoaderRoute: typeof ServicesPlanterWaterproofingCoatingRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/deck-waterproofing-coating-repair': {
      id: '/services/deck-waterproofing-coating-repair'
      path: '/services/deck-waterproofing-coating-repair'
      fullPath: '/services/deck-waterproofing-coating-repair'
      preLoaderRoute: typeof ServicesDeckWaterproofingCoatingRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/balcony-waterproofing-coating-repair': {
      id: '/services/balcony-waterproofing-coating-repair'
      path: '/services/balcony-waterproofing-coating-repair'
      fullPath: '/services/balcony-waterproofing-coating-repair'
      preLoaderRoute: typeof ServicesBalconyWaterproofingCoatingRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-9': {
      id: '/blogs/blog-9'
      path: '/blogs/blog-9'
      fullPath: '/blogs/blog-9'
      preLoaderRoute: typeof BlogsBlog9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-8': {
      id: '/blogs/blog-8'
      path: '/blogs/blog-8'
      fullPath: '/blogs/blog-8'
      preLoaderRoute: typeof BlogsBlog8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-7': {
      id: '/blogs/blog-7'
      path: '/blogs/blog-7'
      fullPath: '/blogs/blog-7'
      preLoaderRoute: typeof BlogsBlog7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-6': {
      id: '/blogs/blog-6'
      path: '/blogs/blog-6'
      fullPath: '/blogs/blog-6'
      preLoaderRoute: typeof BlogsBlog6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-5': {
      id: '/blogs/blog-5'
      path: '/blogs/blog-5'
      fullPath: '/blogs/blog-5'
      preLoaderRoute: typeof BlogsBlog5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-4': {
      id: '/blogs/blog-4'
      path: '/blogs/blog-4'
      fullPath: '/blogs/blog-4'
      preLoaderRoute: typeof BlogsBlog4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-3': {
      id: '/blogs/blog-3'
      path: '/blogs/blog-3'
      fullPath: '/blogs/blog-3'
      preLoaderRoute: typeof BlogsBlog3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-20': {
      id: '/blogs/blog-20'
      path: '/blogs/blog-20'
      fullPath: '/blogs/blog-20'
      preLoaderRoute: typeof BlogsBlog20RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-2': {
      id: '/blogs/blog-2'
      path: '/blogs/blog-2'
      fullPath: '/blogs/blog-2'
      preLoaderRoute: typeof BlogsBlog2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-19': {
      id: '/blogs/blog-19'
      path: '/blogs/blog-19'
      fullPath: '/blogs/blog-19'
      preLoaderRoute: typeof BlogsBlog19RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-18': {
      id: '/blogs/blog-18'
      path: '/blogs/blog-18'
      fullPath: '/blogs/blog-18'
      preLoaderRoute: typeof BlogsBlog18RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-17': {
      id: '/blogs/blog-17'
      path: '/blogs/blog-17'
      fullPath: '/blogs/blog-17'
      preLoaderRoute: typeof BlogsBlog17RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-16': {
      id: '/blogs/blog-16'
      path: '/blogs/blog-16'
      fullPath: '/blogs/blog-16'
      preLoaderRoute: typeof BlogsBlog16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-15': {
      id: '/blogs/blog-15'
      path: '/blogs/blog-15'
      fullPath: '/blogs/blog-15'
      preLoaderRoute: typeof BlogsBlog15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-14': {
      id: '/blogs/blog-14'
      path: '/blogs/blog-14'
      fullPath: '/blogs/blog-14'
      preLoaderRoute: typeof BlogsBlog14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-13': {
      id: '/blogs/blog-13'
      path: '/blogs/blog-13'
      fullPath: '/blogs/blog-13'
      preLoaderRoute: typeof BlogsBlog13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-12': {
      id: '/blogs/blog-12'
      path: '/blogs/blog-12'
      fullPath: '/blogs/blog-12'
      preLoaderRoute: typeof BlogsBlog12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-11': {
      id: '/blogs/blog-11'
      path: '/blogs/blog-11'
      fullPath: '/blogs/blog-11'
      preLoaderRoute: typeof BlogsBlog11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-10': {
      id: '/blogs/blog-10'
      path: '/blogs/blog-10'
      fullPath: '/blogs/blog-10'
      preLoaderRoute: typeof BlogsBlog10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-1': {
      id: '/blogs/blog-1'
      path: '/blogs/blog-1'
      fullPath: '/blogs/blog-1'
      preLoaderRoute: typeof BlogsBlog1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ServiceRoute: ServiceRoute,
  BlogsBlog1Route: BlogsBlog1Route,
  BlogsBlog10Route: BlogsBlog10Route,
  BlogsBlog11Route: BlogsBlog11Route,
  BlogsBlog12Route: BlogsBlog12Route,
  BlogsBlog13Route: BlogsBlog13Route,
  BlogsBlog14Route: BlogsBlog14Route,
  BlogsBlog15Route: BlogsBlog15Route,
  BlogsBlog16Route: BlogsBlog16Route,
  BlogsBlog17Route: BlogsBlog17Route,
  BlogsBlog18Route: BlogsBlog18Route,
  BlogsBlog19Route: BlogsBlog19Route,
  BlogsBlog2Route: BlogsBlog2Route,
  BlogsBlog20Route: BlogsBlog20Route,
  BlogsBlog3Route: BlogsBlog3Route,
  BlogsBlog4Route: BlogsBlog4Route,
  BlogsBlog5Route: BlogsBlog5Route,
  BlogsBlog6Route: BlogsBlog6Route,
  BlogsBlog7Route: BlogsBlog7Route,
  BlogsBlog8Route: BlogsBlog8Route,
  BlogsBlog9Route: BlogsBlog9Route,
  ServicesBalconyWaterproofingCoatingRepairRoute:
    ServicesBalconyWaterproofingCoatingRepairRoute,
  ServicesDeckWaterproofingCoatingRepairRoute:
    ServicesDeckWaterproofingCoatingRepairRoute,
  ServicesPlanterWaterproofingCoatingRepairRoute:
    ServicesPlanterWaterproofingCoatingRepairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
